# Configuration File, Here we configure all the services

server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
    
    
# below is the configuration of services
    
  cloud:
    gateway:
      mvc:
        routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
          - Path=/users/**
#          - Path=/users/**,/secondpath/**,/thirdpath/**    configure multiple url's    Path=/** is used for all [routes all the incoming request here].


#[Recommended] always use the proper url's for ex  Path=/http://localhost/users/userid/222
 

          
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
          - Path=/ratings/**
          
        - id: RESTAURANTSERVICE
          uri: lb://RESTAURANTSERVICE
          predicates:
          - Path=/restaurants/**,/staffs/**
          
          
          
          
          
# Okta Configuration

# Issuer & Audience  - Go to Security Section  ->  API ->  default ->  issuer  [copy & paste here]
# Client ID & Client Secret - Go to Application ->  yourApplicationName ->  Client ID


okta:
  oauth2:
    issuer: https://dev-91270710.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaiksqpb6JihXdcb5d7
    client-secret: LoYlFp96EcKBAeYaJ0Afi9ykXlBvw4G9fpN-tQKPfCS2QIdM7zfOLc5dXjD-Cxlw
    scopes: internal, openid, email, profile,  offline_access # these scopes will be consider from okta when request is coming.
    


          
          
          
          
          