server:
  port: 8085
  
  
spring:
  application:
    name: CONFIG-SERVICE
     
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmanSinghRajawat/DurgeshMicroservices
          clone-on-start: true
          